/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.5 Mon Sep  2 11:07:53 2024.
 */

#include <string.h>

#include "ifcb.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int ifcb_d_space_rl_setpoints1_pack(
    uint8_t *dst_p,
    const struct ifcb_d_space_rl_setpoints1_t *src_p,
    size_t size)
{
    uint16_t amk_target_velocity;
    uint16_t amk_torque_limit_negativ;
    uint16_t amk_torque_limit_positiv;
    uint8_t amk_dc_on;
    uint8_t amk_enable;
    uint8_t amk_error_reset;
    uint8_t amk_inverter_on;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    amk_inverter_on = (uint8_t)src_p->amk_inverter_on;
    dst_p[1] |= pack_left_shift_u8(amk_inverter_on, 0u, 0x01u);
    amk_dc_on = (uint8_t)src_p->amk_dc_on;
    dst_p[1] |= pack_left_shift_u8(amk_dc_on, 1u, 0x02u);
    amk_enable = (uint8_t)src_p->amk_enable;
    dst_p[1] |= pack_left_shift_u8(amk_enable, 2u, 0x04u);
    amk_error_reset = (uint8_t)src_p->amk_error_reset;
    dst_p[1] |= pack_left_shift_u8(amk_error_reset, 3u, 0x08u);
    amk_target_velocity = (uint16_t)src_p->amk_target_velocity;
    dst_p[2] |= pack_left_shift_u16(amk_target_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(amk_target_velocity, 8u, 0xffu);
    amk_torque_limit_positiv = (uint16_t)src_p->amk_torque_limit_positiv;
    dst_p[4] |= pack_left_shift_u16(amk_torque_limit_positiv, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(amk_torque_limit_positiv, 8u, 0xffu);
    amk_torque_limit_negativ = (uint16_t)src_p->amk_torque_limit_negativ;
    dst_p[6] |= pack_left_shift_u16(amk_torque_limit_negativ, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(amk_torque_limit_negativ, 8u, 0xffu);

    return (8);
}

int ifcb_d_space_rl_setpoints1_unpack(
    struct ifcb_d_space_rl_setpoints1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t amk_target_velocity;
    uint16_t amk_torque_limit_negativ;
    uint16_t amk_torque_limit_positiv;
    uint8_t amk_dc_on;
    uint8_t amk_enable;
    uint8_t amk_error_reset;
    uint8_t amk_inverter_on;

    if (size < 8u) {
        return (-EINVAL);
    }

    amk_inverter_on = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    if ((amk_inverter_on & (1u << 0)) != 0u) {
        amk_inverter_on |= 0xfeu;
    }

    dst_p->amk_inverter_on = (int8_t)amk_inverter_on;
    amk_dc_on = unpack_right_shift_u8(src_p[1], 1u, 0x02u);

    if ((amk_dc_on & (1u << 0)) != 0u) {
        amk_dc_on |= 0xfeu;
    }

    dst_p->amk_dc_on = (int8_t)amk_dc_on;
    amk_enable = unpack_right_shift_u8(src_p[1], 2u, 0x04u);

    if ((amk_enable & (1u << 0)) != 0u) {
        amk_enable |= 0xfeu;
    }

    dst_p->amk_enable = (int8_t)amk_enable;
    amk_error_reset = unpack_right_shift_u8(src_p[1], 3u, 0x08u);

    if ((amk_error_reset & (1u << 0)) != 0u) {
        amk_error_reset |= 0xfeu;
    }

    dst_p->amk_error_reset = (int8_t)amk_error_reset;
    amk_target_velocity = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    amk_target_velocity |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->amk_target_velocity = (int16_t)amk_target_velocity;
    amk_torque_limit_positiv = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    amk_torque_limit_positiv |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->amk_torque_limit_positiv = (int16_t)amk_torque_limit_positiv;
    amk_torque_limit_negativ = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    amk_torque_limit_negativ |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->amk_torque_limit_negativ = (int16_t)amk_torque_limit_negativ;

    return (0);
}

int ifcb_d_space_rl_setpoints1_init(struct ifcb_d_space_rl_setpoints1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ifcb_d_space_rl_setpoints1_t));

    return 0;
}

int8_t ifcb_d_space_rl_setpoints1_amk_inverter_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_rl_setpoints1_amk_inverter_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_rl_setpoints1_amk_inverter_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_d_space_rl_setpoints1_amk_dc_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_rl_setpoints1_amk_dc_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_rl_setpoints1_amk_dc_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_d_space_rl_setpoints1_amk_enable_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_rl_setpoints1_amk_enable_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_rl_setpoints1_amk_enable_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_d_space_rl_setpoints1_amk_error_reset_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_rl_setpoints1_amk_error_reset_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_rl_setpoints1_amk_error_reset_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int16_t ifcb_d_space_rl_setpoints1_amk_target_velocity_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_d_space_rl_setpoints1_amk_target_velocity_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_d_space_rl_setpoints1_amk_target_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_d_space_rl_setpoints1_amk_torque_limit_positiv_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_d_space_rl_setpoints1_amk_torque_limit_positiv_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_d_space_rl_setpoints1_amk_torque_limit_positiv_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_d_space_rl_setpoints1_amk_torque_limit_negativ_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_d_space_rl_setpoints1_amk_torque_limit_negativ_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_d_space_rl_setpoints1_amk_torque_limit_negativ_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ifcb_d_space_fl_setpoints1_pack(
    uint8_t *dst_p,
    const struct ifcb_d_space_fl_setpoints1_t *src_p,
    size_t size)
{
    uint16_t amk_target_velocity;
    uint16_t amk_torque_limit_negativ;
    uint16_t amk_torque_limit_positiv;
    uint8_t amk_dc_on;
    uint8_t amk_enable;
    uint8_t amk_error_reset;
    uint8_t amk_inverter_on;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    amk_inverter_on = (uint8_t)src_p->amk_inverter_on;
    dst_p[1] |= pack_left_shift_u8(amk_inverter_on, 0u, 0x01u);
    amk_dc_on = (uint8_t)src_p->amk_dc_on;
    dst_p[1] |= pack_left_shift_u8(amk_dc_on, 1u, 0x02u);
    amk_enable = (uint8_t)src_p->amk_enable;
    dst_p[1] |= pack_left_shift_u8(amk_enable, 2u, 0x04u);
    amk_error_reset = (uint8_t)src_p->amk_error_reset;
    dst_p[1] |= pack_left_shift_u8(amk_error_reset, 3u, 0x08u);
    amk_target_velocity = (uint16_t)src_p->amk_target_velocity;
    dst_p[2] |= pack_left_shift_u16(amk_target_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(amk_target_velocity, 8u, 0xffu);
    amk_torque_limit_positiv = (uint16_t)src_p->amk_torque_limit_positiv;
    dst_p[4] |= pack_left_shift_u16(amk_torque_limit_positiv, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(amk_torque_limit_positiv, 8u, 0xffu);
    amk_torque_limit_negativ = (uint16_t)src_p->amk_torque_limit_negativ;
    dst_p[6] |= pack_left_shift_u16(amk_torque_limit_negativ, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(amk_torque_limit_negativ, 8u, 0xffu);

    return (8);
}

int ifcb_d_space_fl_setpoints1_unpack(
    struct ifcb_d_space_fl_setpoints1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t amk_target_velocity;
    uint16_t amk_torque_limit_negativ;
    uint16_t amk_torque_limit_positiv;
    uint8_t amk_dc_on;
    uint8_t amk_enable;
    uint8_t amk_error_reset;
    uint8_t amk_inverter_on;

    if (size < 8u) {
        return (-EINVAL);
    }

    amk_inverter_on = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    if ((amk_inverter_on & (1u << 0)) != 0u) {
        amk_inverter_on |= 0xfeu;
    }

    dst_p->amk_inverter_on = (int8_t)amk_inverter_on;
    amk_dc_on = unpack_right_shift_u8(src_p[1], 1u, 0x02u);

    if ((amk_dc_on & (1u << 0)) != 0u) {
        amk_dc_on |= 0xfeu;
    }

    dst_p->amk_dc_on = (int8_t)amk_dc_on;
    amk_enable = unpack_right_shift_u8(src_p[1], 2u, 0x04u);

    if ((amk_enable & (1u << 0)) != 0u) {
        amk_enable |= 0xfeu;
    }

    dst_p->amk_enable = (int8_t)amk_enable;
    amk_error_reset = unpack_right_shift_u8(src_p[1], 3u, 0x08u);

    if ((amk_error_reset & (1u << 0)) != 0u) {
        amk_error_reset |= 0xfeu;
    }

    dst_p->amk_error_reset = (int8_t)amk_error_reset;
    amk_target_velocity = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    amk_target_velocity |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->amk_target_velocity = (int16_t)amk_target_velocity;
    amk_torque_limit_positiv = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    amk_torque_limit_positiv |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->amk_torque_limit_positiv = (int16_t)amk_torque_limit_positiv;
    amk_torque_limit_negativ = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    amk_torque_limit_negativ |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->amk_torque_limit_negativ = (int16_t)amk_torque_limit_negativ;

    return (0);
}

int ifcb_d_space_fl_setpoints1_init(struct ifcb_d_space_fl_setpoints1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ifcb_d_space_fl_setpoints1_t));

    return 0;
}

int8_t ifcb_d_space_fl_setpoints1_amk_inverter_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_fl_setpoints1_amk_inverter_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_fl_setpoints1_amk_inverter_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_d_space_fl_setpoints1_amk_dc_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_fl_setpoints1_amk_dc_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_fl_setpoints1_amk_dc_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_d_space_fl_setpoints1_amk_enable_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_fl_setpoints1_amk_enable_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_fl_setpoints1_amk_enable_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_d_space_fl_setpoints1_amk_error_reset_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_fl_setpoints1_amk_error_reset_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_fl_setpoints1_amk_error_reset_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int16_t ifcb_d_space_fl_setpoints1_amk_target_velocity_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_d_space_fl_setpoints1_amk_target_velocity_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_d_space_fl_setpoints1_amk_target_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_d_space_fl_setpoints1_amk_torque_limit_positiv_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_d_space_fl_setpoints1_amk_torque_limit_positiv_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_d_space_fl_setpoints1_amk_torque_limit_positiv_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_d_space_fl_setpoints1_amk_torque_limit_negativ_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_d_space_fl_setpoints1_amk_torque_limit_negativ_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_d_space_fl_setpoints1_amk_torque_limit_negativ_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ifcb_d_space_rr_setpoints1_pack(
    uint8_t *dst_p,
    const struct ifcb_d_space_rr_setpoints1_t *src_p,
    size_t size)
{
    uint16_t amk_target_velocity;
    uint16_t amk_torque_limit_negativ;
    uint16_t amk_torque_limit_positiv;
    uint8_t amk_dc_on;
    uint8_t amk_enable;
    uint8_t amk_error_reset;
    uint8_t amk_inverter_on;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    amk_inverter_on = (uint8_t)src_p->amk_inverter_on;
    dst_p[1] |= pack_left_shift_u8(amk_inverter_on, 0u, 0x01u);
    amk_dc_on = (uint8_t)src_p->amk_dc_on;
    dst_p[1] |= pack_left_shift_u8(amk_dc_on, 1u, 0x02u);
    amk_enable = (uint8_t)src_p->amk_enable;
    dst_p[1] |= pack_left_shift_u8(amk_enable, 2u, 0x04u);
    amk_error_reset = (uint8_t)src_p->amk_error_reset;
    dst_p[1] |= pack_left_shift_u8(amk_error_reset, 3u, 0x08u);
    amk_target_velocity = (uint16_t)src_p->amk_target_velocity;
    dst_p[2] |= pack_left_shift_u16(amk_target_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(amk_target_velocity, 8u, 0xffu);
    amk_torque_limit_positiv = (uint16_t)src_p->amk_torque_limit_positiv;
    dst_p[4] |= pack_left_shift_u16(amk_torque_limit_positiv, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(amk_torque_limit_positiv, 8u, 0xffu);
    amk_torque_limit_negativ = (uint16_t)src_p->amk_torque_limit_negativ;
    dst_p[6] |= pack_left_shift_u16(amk_torque_limit_negativ, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(amk_torque_limit_negativ, 8u, 0xffu);

    return (8);
}

int ifcb_d_space_rr_setpoints1_unpack(
    struct ifcb_d_space_rr_setpoints1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t amk_target_velocity;
    uint16_t amk_torque_limit_negativ;
    uint16_t amk_torque_limit_positiv;
    uint8_t amk_dc_on;
    uint8_t amk_enable;
    uint8_t amk_error_reset;
    uint8_t amk_inverter_on;

    if (size < 8u) {
        return (-EINVAL);
    }

    amk_inverter_on = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    if ((amk_inverter_on & (1u << 0)) != 0u) {
        amk_inverter_on |= 0xfeu;
    }

    dst_p->amk_inverter_on = (int8_t)amk_inverter_on;
    amk_dc_on = unpack_right_shift_u8(src_p[1], 1u, 0x02u);

    if ((amk_dc_on & (1u << 0)) != 0u) {
        amk_dc_on |= 0xfeu;
    }

    dst_p->amk_dc_on = (int8_t)amk_dc_on;
    amk_enable = unpack_right_shift_u8(src_p[1], 2u, 0x04u);

    if ((amk_enable & (1u << 0)) != 0u) {
        amk_enable |= 0xfeu;
    }

    dst_p->amk_enable = (int8_t)amk_enable;
    amk_error_reset = unpack_right_shift_u8(src_p[1], 3u, 0x08u);

    if ((amk_error_reset & (1u << 0)) != 0u) {
        amk_error_reset |= 0xfeu;
    }

    dst_p->amk_error_reset = (int8_t)amk_error_reset;
    amk_target_velocity = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    amk_target_velocity |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->amk_target_velocity = (int16_t)amk_target_velocity;
    amk_torque_limit_positiv = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    amk_torque_limit_positiv |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->amk_torque_limit_positiv = (int16_t)amk_torque_limit_positiv;
    amk_torque_limit_negativ = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    amk_torque_limit_negativ |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->amk_torque_limit_negativ = (int16_t)amk_torque_limit_negativ;

    return (0);
}

int ifcb_d_space_rr_setpoints1_init(struct ifcb_d_space_rr_setpoints1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ifcb_d_space_rr_setpoints1_t));

    return 0;
}

int8_t ifcb_d_space_rr_setpoints1_amk_inverter_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_rr_setpoints1_amk_inverter_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_rr_setpoints1_amk_inverter_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_d_space_rr_setpoints1_amk_dc_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_rr_setpoints1_amk_dc_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_rr_setpoints1_amk_dc_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_d_space_rr_setpoints1_amk_enable_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_rr_setpoints1_amk_enable_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_rr_setpoints1_amk_enable_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_d_space_rr_setpoints1_amk_error_reset_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_rr_setpoints1_amk_error_reset_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_rr_setpoints1_amk_error_reset_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int16_t ifcb_d_space_rr_setpoints1_amk_target_velocity_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_d_space_rr_setpoints1_amk_target_velocity_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_d_space_rr_setpoints1_amk_target_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_d_space_rr_setpoints1_amk_torque_limit_positiv_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_d_space_rr_setpoints1_amk_torque_limit_positiv_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_d_space_rr_setpoints1_amk_torque_limit_positiv_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_d_space_rr_setpoints1_amk_torque_limit_negativ_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_d_space_rr_setpoints1_amk_torque_limit_negativ_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_d_space_rr_setpoints1_amk_torque_limit_negativ_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ifcb_d_space_fr_setpoints1_pack(
    uint8_t *dst_p,
    const struct ifcb_d_space_fr_setpoints1_t *src_p,
    size_t size)
{
    uint16_t amk_target_velocity;
    uint16_t amk_torque_limit_negativ;
    uint16_t amk_torque_limit_positiv;
    uint8_t amk_dc_on;
    uint8_t amk_enable;
    uint8_t amk_error_reset;
    uint8_t amk_inverter_on;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    amk_inverter_on = (uint8_t)src_p->amk_inverter_on;
    dst_p[1] |= pack_left_shift_u8(amk_inverter_on, 0u, 0x01u);
    amk_dc_on = (uint8_t)src_p->amk_dc_on;
    dst_p[1] |= pack_left_shift_u8(amk_dc_on, 1u, 0x02u);
    amk_enable = (uint8_t)src_p->amk_enable;
    dst_p[1] |= pack_left_shift_u8(amk_enable, 2u, 0x04u);
    amk_error_reset = (uint8_t)src_p->amk_error_reset;
    dst_p[1] |= pack_left_shift_u8(amk_error_reset, 3u, 0x08u);
    amk_target_velocity = (uint16_t)src_p->amk_target_velocity;
    dst_p[2] |= pack_left_shift_u16(amk_target_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(amk_target_velocity, 8u, 0xffu);
    amk_torque_limit_positiv = (uint16_t)src_p->amk_torque_limit_positiv;
    dst_p[4] |= pack_left_shift_u16(amk_torque_limit_positiv, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(amk_torque_limit_positiv, 8u, 0xffu);
    amk_torque_limit_negativ = (uint16_t)src_p->amk_torque_limit_negativ;
    dst_p[6] |= pack_left_shift_u16(amk_torque_limit_negativ, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(amk_torque_limit_negativ, 8u, 0xffu);

    return (8);
}

int ifcb_d_space_fr_setpoints1_unpack(
    struct ifcb_d_space_fr_setpoints1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t amk_target_velocity;
    uint16_t amk_torque_limit_negativ;
    uint16_t amk_torque_limit_positiv;
    uint8_t amk_dc_on;
    uint8_t amk_enable;
    uint8_t amk_error_reset;
    uint8_t amk_inverter_on;

    if (size < 8u) {
        return (-EINVAL);
    }

    amk_inverter_on = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    if ((amk_inverter_on & (1u << 0)) != 0u) {
        amk_inverter_on |= 0xfeu;
    }

    dst_p->amk_inverter_on = (int8_t)amk_inverter_on;
    amk_dc_on = unpack_right_shift_u8(src_p[1], 1u, 0x02u);

    if ((amk_dc_on & (1u << 0)) != 0u) {
        amk_dc_on |= 0xfeu;
    }

    dst_p->amk_dc_on = (int8_t)amk_dc_on;
    amk_enable = unpack_right_shift_u8(src_p[1], 2u, 0x04u);

    if ((amk_enable & (1u << 0)) != 0u) {
        amk_enable |= 0xfeu;
    }

    dst_p->amk_enable = (int8_t)amk_enable;
    amk_error_reset = unpack_right_shift_u8(src_p[1], 3u, 0x08u);

    if ((amk_error_reset & (1u << 0)) != 0u) {
        amk_error_reset |= 0xfeu;
    }

    dst_p->amk_error_reset = (int8_t)amk_error_reset;
    amk_target_velocity = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    amk_target_velocity |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->amk_target_velocity = (int16_t)amk_target_velocity;
    amk_torque_limit_positiv = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    amk_torque_limit_positiv |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->amk_torque_limit_positiv = (int16_t)amk_torque_limit_positiv;
    amk_torque_limit_negativ = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    amk_torque_limit_negativ |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->amk_torque_limit_negativ = (int16_t)amk_torque_limit_negativ;

    return (0);
}

int ifcb_d_space_fr_setpoints1_init(struct ifcb_d_space_fr_setpoints1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ifcb_d_space_fr_setpoints1_t));

    return 0;
}

int8_t ifcb_d_space_fr_setpoints1_amk_inverter_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_fr_setpoints1_amk_inverter_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_fr_setpoints1_amk_inverter_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_d_space_fr_setpoints1_amk_dc_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_fr_setpoints1_amk_dc_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_fr_setpoints1_amk_dc_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_d_space_fr_setpoints1_amk_enable_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_fr_setpoints1_amk_enable_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_fr_setpoints1_amk_enable_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_d_space_fr_setpoints1_amk_error_reset_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_d_space_fr_setpoints1_amk_error_reset_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_d_space_fr_setpoints1_amk_error_reset_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int16_t ifcb_d_space_fr_setpoints1_amk_target_velocity_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_d_space_fr_setpoints1_amk_target_velocity_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_d_space_fr_setpoints1_amk_target_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_d_space_fr_setpoints1_amk_torque_limit_positiv_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_d_space_fr_setpoints1_amk_torque_limit_positiv_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_d_space_fr_setpoints1_amk_torque_limit_positiv_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_d_space_fr_setpoints1_amk_torque_limit_negativ_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_d_space_fr_setpoints1_amk_torque_limit_negativ_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_d_space_fr_setpoints1_amk_torque_limit_negativ_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ifcb_inverter_rl_actual_values1_pack(
    uint8_t *dst_p,
    const struct ifcb_inverter_rl_actual_values1_t *src_p,
    size_t size)
{
    uint16_t amk_actual_velocity;
    uint16_t amk_magnetizing_current;
    uint16_t amk_torque_current;
    uint8_t amk_dc_on;
    uint8_t amk_derating;
    uint8_t amk_error;
    uint8_t amk_inverter_on;
    uint8_t amk_quit_dc_on;
    uint8_t amk_quit_inverter_on;
    uint8_t amk_system_ready;
    uint8_t amk_warning;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    amk_system_ready = (uint8_t)src_p->amk_system_ready;
    dst_p[1] |= pack_left_shift_u8(amk_system_ready, 0u, 0x01u);
    amk_error = (uint8_t)src_p->amk_error;
    dst_p[1] |= pack_left_shift_u8(amk_error, 1u, 0x02u);
    amk_warning = (uint8_t)src_p->amk_warning;
    dst_p[1] |= pack_left_shift_u8(amk_warning, 2u, 0x04u);
    amk_quit_dc_on = (uint8_t)src_p->amk_quit_dc_on;
    dst_p[1] |= pack_left_shift_u8(amk_quit_dc_on, 3u, 0x08u);
    amk_dc_on = (uint8_t)src_p->amk_dc_on;
    dst_p[1] |= pack_left_shift_u8(amk_dc_on, 4u, 0x10u);
    amk_quit_inverter_on = (uint8_t)src_p->amk_quit_inverter_on;
    dst_p[1] |= pack_left_shift_u8(amk_quit_inverter_on, 5u, 0x20u);
    amk_inverter_on = (uint8_t)src_p->amk_inverter_on;
    dst_p[1] |= pack_left_shift_u8(amk_inverter_on, 6u, 0x40u);
    amk_derating = (uint8_t)src_p->amk_derating;
    dst_p[1] |= pack_left_shift_u8(amk_derating, 7u, 0x80u);
    amk_actual_velocity = (uint16_t)src_p->amk_actual_velocity;
    dst_p[2] |= pack_left_shift_u16(amk_actual_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(amk_actual_velocity, 8u, 0xffu);
    amk_torque_current = (uint16_t)src_p->amk_torque_current;
    dst_p[4] |= pack_left_shift_u16(amk_torque_current, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(amk_torque_current, 8u, 0xffu);
    amk_magnetizing_current = (uint16_t)src_p->amk_magnetizing_current;
    dst_p[6] |= pack_left_shift_u16(amk_magnetizing_current, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(amk_magnetizing_current, 8u, 0xffu);

    return (8);
}

int ifcb_inverter_rl_actual_values1_unpack(
    struct ifcb_inverter_rl_actual_values1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t amk_actual_velocity;
    uint16_t amk_magnetizing_current;
    uint16_t amk_torque_current;
    uint8_t amk_dc_on;
    uint8_t amk_derating;
    uint8_t amk_error;
    uint8_t amk_inverter_on;
    uint8_t amk_quit_dc_on;
    uint8_t amk_quit_inverter_on;
    uint8_t amk_system_ready;
    uint8_t amk_warning;

    if (size < 8u) {
        return (-EINVAL);
    }

    amk_system_ready = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    if ((amk_system_ready & (1u << 0)) != 0u) {
        amk_system_ready |= 0xfeu;
    }

    dst_p->amk_system_ready = (int8_t)amk_system_ready;
    amk_error = unpack_right_shift_u8(src_p[1], 1u, 0x02u);

    if ((amk_error & (1u << 0)) != 0u) {
        amk_error |= 0xfeu;
    }

    dst_p->amk_error = (int8_t)amk_error;
    amk_warning = unpack_right_shift_u8(src_p[1], 2u, 0x04u);

    if ((amk_warning & (1u << 0)) != 0u) {
        amk_warning |= 0xfeu;
    }

    dst_p->amk_warning = (int8_t)amk_warning;
    amk_quit_dc_on = unpack_right_shift_u8(src_p[1], 3u, 0x08u);

    if ((amk_quit_dc_on & (1u << 0)) != 0u) {
        amk_quit_dc_on |= 0xfeu;
    }

    dst_p->amk_quit_dc_on = (int8_t)amk_quit_dc_on;
    amk_dc_on = unpack_right_shift_u8(src_p[1], 4u, 0x10u);

    if ((amk_dc_on & (1u << 0)) != 0u) {
        amk_dc_on |= 0xfeu;
    }

    dst_p->amk_dc_on = (int8_t)amk_dc_on;
    amk_quit_inverter_on = unpack_right_shift_u8(src_p[1], 5u, 0x20u);

    if ((amk_quit_inverter_on & (1u << 0)) != 0u) {
        amk_quit_inverter_on |= 0xfeu;
    }

    dst_p->amk_quit_inverter_on = (int8_t)amk_quit_inverter_on;
    amk_inverter_on = unpack_right_shift_u8(src_p[1], 6u, 0x40u);

    if ((amk_inverter_on & (1u << 0)) != 0u) {
        amk_inverter_on |= 0xfeu;
    }

    dst_p->amk_inverter_on = (int8_t)amk_inverter_on;
    amk_derating = unpack_right_shift_u8(src_p[1], 7u, 0x80u);

    if ((amk_derating & (1u << 0)) != 0u) {
        amk_derating |= 0xfeu;
    }

    dst_p->amk_derating = (int8_t)amk_derating;
    amk_actual_velocity = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    amk_actual_velocity |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->amk_actual_velocity = (int16_t)amk_actual_velocity;
    amk_torque_current = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    amk_torque_current |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->amk_torque_current = (int16_t)amk_torque_current;
    amk_magnetizing_current = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    amk_magnetizing_current |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->amk_magnetizing_current = (int16_t)amk_magnetizing_current;

    return (0);
}

int ifcb_inverter_rl_actual_values1_init(struct ifcb_inverter_rl_actual_values1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ifcb_inverter_rl_actual_values1_t));

    return 0;
}

int8_t ifcb_inverter_rl_actual_values1_amk_system_ready_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rl_actual_values1_amk_system_ready_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rl_actual_values1_amk_system_ready_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_rl_actual_values1_amk_error_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rl_actual_values1_amk_error_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rl_actual_values1_amk_error_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_rl_actual_values1_amk_warning_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rl_actual_values1_amk_warning_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rl_actual_values1_amk_warning_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_rl_actual_values1_amk_quit_dc_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rl_actual_values1_amk_quit_dc_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rl_actual_values1_amk_quit_dc_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_rl_actual_values1_amk_dc_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rl_actual_values1_amk_dc_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rl_actual_values1_amk_dc_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_rl_actual_values1_amk_quit_inverter_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rl_actual_values1_amk_quit_inverter_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rl_actual_values1_amk_quit_inverter_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_rl_actual_values1_amk_inverter_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rl_actual_values1_amk_inverter_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rl_actual_values1_amk_inverter_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_rl_actual_values1_amk_derating_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rl_actual_values1_amk_derating_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rl_actual_values1_amk_derating_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int16_t ifcb_inverter_rl_actual_values1_amk_actual_velocity_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_inverter_rl_actual_values1_amk_actual_velocity_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rl_actual_values1_amk_actual_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_inverter_rl_actual_values1_amk_torque_current_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_inverter_rl_actual_values1_amk_torque_current_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rl_actual_values1_amk_torque_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_inverter_rl_actual_values1_amk_magnetizing_current_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_inverter_rl_actual_values1_amk_magnetizing_current_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rl_actual_values1_amk_magnetizing_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ifcb_inverter_fl_actual_values1_pack(
    uint8_t *dst_p,
    const struct ifcb_inverter_fl_actual_values1_t *src_p,
    size_t size)
{
    uint16_t amk_actual_velocity;
    uint16_t amk_magnetizing_current;
    uint16_t amk_torque_current;
    uint8_t amk_dc_on;
    uint8_t amk_derating;
    uint8_t amk_error;
    uint8_t amk_inverter_on;
    uint8_t amk_quit_dc_on;
    uint8_t amk_quit_inverter_on;
    uint8_t amk_system_ready;
    uint8_t amk_warning;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    amk_system_ready = (uint8_t)src_p->amk_system_ready;
    dst_p[1] |= pack_left_shift_u8(amk_system_ready, 0u, 0x01u);
    amk_error = (uint8_t)src_p->amk_error;
    dst_p[1] |= pack_left_shift_u8(amk_error, 1u, 0x02u);
    amk_warning = (uint8_t)src_p->amk_warning;
    dst_p[1] |= pack_left_shift_u8(amk_warning, 2u, 0x04u);
    amk_quit_dc_on = (uint8_t)src_p->amk_quit_dc_on;
    dst_p[1] |= pack_left_shift_u8(amk_quit_dc_on, 3u, 0x08u);
    amk_dc_on = (uint8_t)src_p->amk_dc_on;
    dst_p[1] |= pack_left_shift_u8(amk_dc_on, 4u, 0x10u);
    amk_quit_inverter_on = (uint8_t)src_p->amk_quit_inverter_on;
    dst_p[1] |= pack_left_shift_u8(amk_quit_inverter_on, 5u, 0x20u);
    amk_inverter_on = (uint8_t)src_p->amk_inverter_on;
    dst_p[1] |= pack_left_shift_u8(amk_inverter_on, 6u, 0x40u);
    amk_derating = (uint8_t)src_p->amk_derating;
    dst_p[1] |= pack_left_shift_u8(amk_derating, 7u, 0x80u);
    amk_actual_velocity = (uint16_t)src_p->amk_actual_velocity;
    dst_p[2] |= pack_left_shift_u16(amk_actual_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(amk_actual_velocity, 8u, 0xffu);
    amk_torque_current = (uint16_t)src_p->amk_torque_current;
    dst_p[4] |= pack_left_shift_u16(amk_torque_current, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(amk_torque_current, 8u, 0xffu);
    amk_magnetizing_current = (uint16_t)src_p->amk_magnetizing_current;
    dst_p[6] |= pack_left_shift_u16(amk_magnetizing_current, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(amk_magnetizing_current, 8u, 0xffu);

    return (8);
}

int ifcb_inverter_fl_actual_values1_unpack(
    struct ifcb_inverter_fl_actual_values1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t amk_actual_velocity;
    uint16_t amk_magnetizing_current;
    uint16_t amk_torque_current;
    uint8_t amk_dc_on;
    uint8_t amk_derating;
    uint8_t amk_error;
    uint8_t amk_inverter_on;
    uint8_t amk_quit_dc_on;
    uint8_t amk_quit_inverter_on;
    uint8_t amk_system_ready;
    uint8_t amk_warning;

    if (size < 8u) {
        return (-EINVAL);
    }

    amk_system_ready = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    if ((amk_system_ready & (1u << 0)) != 0u) {
        amk_system_ready |= 0xfeu;
    }

    dst_p->amk_system_ready = (int8_t)amk_system_ready;
    amk_error = unpack_right_shift_u8(src_p[1], 1u, 0x02u);

    if ((amk_error & (1u << 0)) != 0u) {
        amk_error |= 0xfeu;
    }

    dst_p->amk_error = (int8_t)amk_error;
    amk_warning = unpack_right_shift_u8(src_p[1], 2u, 0x04u);

    if ((amk_warning & (1u << 0)) != 0u) {
        amk_warning |= 0xfeu;
    }

    dst_p->amk_warning = (int8_t)amk_warning;
    amk_quit_dc_on = unpack_right_shift_u8(src_p[1], 3u, 0x08u);

    if ((amk_quit_dc_on & (1u << 0)) != 0u) {
        amk_quit_dc_on |= 0xfeu;
    }

    dst_p->amk_quit_dc_on = (int8_t)amk_quit_dc_on;
    amk_dc_on = unpack_right_shift_u8(src_p[1], 4u, 0x10u);

    if ((amk_dc_on & (1u << 0)) != 0u) {
        amk_dc_on |= 0xfeu;
    }

    dst_p->amk_dc_on = (int8_t)amk_dc_on;
    amk_quit_inverter_on = unpack_right_shift_u8(src_p[1], 5u, 0x20u);

    if ((amk_quit_inverter_on & (1u << 0)) != 0u) {
        amk_quit_inverter_on |= 0xfeu;
    }

    dst_p->amk_quit_inverter_on = (int8_t)amk_quit_inverter_on;
    amk_inverter_on = unpack_right_shift_u8(src_p[1], 6u, 0x40u);

    if ((amk_inverter_on & (1u << 0)) != 0u) {
        amk_inverter_on |= 0xfeu;
    }

    dst_p->amk_inverter_on = (int8_t)amk_inverter_on;
    amk_derating = unpack_right_shift_u8(src_p[1], 7u, 0x80u);

    if ((amk_derating & (1u << 0)) != 0u) {
        amk_derating |= 0xfeu;
    }

    dst_p->amk_derating = (int8_t)amk_derating;
    amk_actual_velocity = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    amk_actual_velocity |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->amk_actual_velocity = (int16_t)amk_actual_velocity;
    amk_torque_current = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    amk_torque_current |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->amk_torque_current = (int16_t)amk_torque_current;
    amk_magnetizing_current = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    amk_magnetizing_current |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->amk_magnetizing_current = (int16_t)amk_magnetizing_current;

    return (0);
}

int ifcb_inverter_fl_actual_values1_init(struct ifcb_inverter_fl_actual_values1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ifcb_inverter_fl_actual_values1_t));

    return 0;
}

int8_t ifcb_inverter_fl_actual_values1_amk_system_ready_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fl_actual_values1_amk_system_ready_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fl_actual_values1_amk_system_ready_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_fl_actual_values1_amk_error_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fl_actual_values1_amk_error_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fl_actual_values1_amk_error_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_fl_actual_values1_amk_warning_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fl_actual_values1_amk_warning_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fl_actual_values1_amk_warning_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_fl_actual_values1_amk_quit_dc_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fl_actual_values1_amk_quit_dc_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fl_actual_values1_amk_quit_dc_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_fl_actual_values1_amk_dc_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fl_actual_values1_amk_dc_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fl_actual_values1_amk_dc_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_fl_actual_values1_amk_quit_inverter_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fl_actual_values1_amk_quit_inverter_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fl_actual_values1_amk_quit_inverter_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_fl_actual_values1_amk_inverter_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fl_actual_values1_amk_inverter_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fl_actual_values1_amk_inverter_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_fl_actual_values1_amk_derating_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fl_actual_values1_amk_derating_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fl_actual_values1_amk_derating_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int16_t ifcb_inverter_fl_actual_values1_amk_actual_velocity_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_inverter_fl_actual_values1_amk_actual_velocity_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fl_actual_values1_amk_actual_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_inverter_fl_actual_values1_amk_torque_current_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_inverter_fl_actual_values1_amk_torque_current_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fl_actual_values1_amk_torque_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_inverter_fl_actual_values1_amk_magnetizing_current_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_inverter_fl_actual_values1_amk_magnetizing_current_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fl_actual_values1_amk_magnetizing_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ifcb_inverter_rl_actual_values2_pack(
    uint8_t *dst_p,
    const struct ifcb_inverter_rl_actual_values2_t *src_p,
    size_t size)
{
    uint16_t amk_igbt_temp;
    uint16_t amk_temp_inverter;
    uint16_t amk_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    amk_temp_motor = (uint16_t)src_p->amk_temp_motor;
    dst_p[0] |= pack_left_shift_u16(amk_temp_motor, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(amk_temp_motor, 8u, 0xffu);
    amk_temp_inverter = (uint16_t)src_p->amk_temp_inverter;
    dst_p[2] |= pack_left_shift_u16(amk_temp_inverter, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(amk_temp_inverter, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->amk_error_info, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->amk_error_info, 8u, 0xffu);
    amk_igbt_temp = (uint16_t)src_p->amk_igbt_temp;
    dst_p[6] |= pack_left_shift_u16(amk_igbt_temp, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(amk_igbt_temp, 8u, 0xffu);

    return (8);
}

int ifcb_inverter_rl_actual_values2_unpack(
    struct ifcb_inverter_rl_actual_values2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t amk_igbt_temp;
    uint16_t amk_temp_inverter;
    uint16_t amk_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    amk_temp_motor = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    amk_temp_motor |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->amk_temp_motor = (int16_t)amk_temp_motor;
    amk_temp_inverter = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    amk_temp_inverter |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->amk_temp_inverter = (int16_t)amk_temp_inverter;
    dst_p->amk_error_info = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->amk_error_info |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    amk_igbt_temp = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    amk_igbt_temp |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->amk_igbt_temp = (int16_t)amk_igbt_temp;

    return (0);
}

int ifcb_inverter_rl_actual_values2_init(struct ifcb_inverter_rl_actual_values2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ifcb_inverter_rl_actual_values2_t));

    return 0;
}

int16_t ifcb_inverter_rl_actual_values2_amk_temp_motor_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double ifcb_inverter_rl_actual_values2_amk_temp_motor_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool ifcb_inverter_rl_actual_values2_amk_temp_motor_is_in_range(int16_t value)
{
    return ((value >= -32760) && (value <= 32760));
}

int16_t ifcb_inverter_rl_actual_values2_amk_temp_inverter_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double ifcb_inverter_rl_actual_values2_amk_temp_inverter_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool ifcb_inverter_rl_actual_values2_amk_temp_inverter_is_in_range(int16_t value)
{
    return ((value >= -32760) && (value <= 32760));
}

uint16_t ifcb_inverter_rl_actual_values2_amk_error_info_encode(double value)
{
    return (uint16_t)(value);
}

double ifcb_inverter_rl_actual_values2_amk_error_info_decode(uint16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rl_actual_values2_amk_error_info_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_inverter_rl_actual_values2_amk_igbt_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double ifcb_inverter_rl_actual_values2_amk_igbt_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool ifcb_inverter_rl_actual_values2_amk_igbt_temp_is_in_range(int16_t value)
{
    return ((value >= -32760) && (value <= 32760));
}

int ifcb_inverter_fl_actual_values2_pack(
    uint8_t *dst_p,
    const struct ifcb_inverter_fl_actual_values2_t *src_p,
    size_t size)
{
    uint16_t amk_igbt_temp;
    uint16_t amk_temp_inverter;
    uint16_t amk_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    amk_temp_motor = (uint16_t)src_p->amk_temp_motor;
    dst_p[0] |= pack_left_shift_u16(amk_temp_motor, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(amk_temp_motor, 8u, 0xffu);
    amk_temp_inverter = (uint16_t)src_p->amk_temp_inverter;
    dst_p[2] |= pack_left_shift_u16(amk_temp_inverter, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(amk_temp_inverter, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->amk_error_info, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->amk_error_info, 8u, 0xffu);
    amk_igbt_temp = (uint16_t)src_p->amk_igbt_temp;
    dst_p[6] |= pack_left_shift_u16(amk_igbt_temp, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(amk_igbt_temp, 8u, 0xffu);

    return (8);
}

int ifcb_inverter_fl_actual_values2_unpack(
    struct ifcb_inverter_fl_actual_values2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t amk_igbt_temp;
    uint16_t amk_temp_inverter;
    uint16_t amk_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    amk_temp_motor = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    amk_temp_motor |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->amk_temp_motor = (int16_t)amk_temp_motor;
    amk_temp_inverter = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    amk_temp_inverter |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->amk_temp_inverter = (int16_t)amk_temp_inverter;
    dst_p->amk_error_info = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->amk_error_info |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    amk_igbt_temp = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    amk_igbt_temp |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->amk_igbt_temp = (int16_t)amk_igbt_temp;

    return (0);
}

int ifcb_inverter_fl_actual_values2_init(struct ifcb_inverter_fl_actual_values2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ifcb_inverter_fl_actual_values2_t));

    return 0;
}

int16_t ifcb_inverter_fl_actual_values2_amk_temp_motor_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double ifcb_inverter_fl_actual_values2_amk_temp_motor_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool ifcb_inverter_fl_actual_values2_amk_temp_motor_is_in_range(int16_t value)
{
    return ((value >= -32760) && (value <= 32760));
}

int16_t ifcb_inverter_fl_actual_values2_amk_temp_inverter_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double ifcb_inverter_fl_actual_values2_amk_temp_inverter_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool ifcb_inverter_fl_actual_values2_amk_temp_inverter_is_in_range(int16_t value)
{
    return ((value >= -32760) && (value <= 32760));
}

uint16_t ifcb_inverter_fl_actual_values2_amk_error_info_encode(double value)
{
    return (uint16_t)(value);
}

double ifcb_inverter_fl_actual_values2_amk_error_info_decode(uint16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fl_actual_values2_amk_error_info_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_inverter_fl_actual_values2_amk_igbt_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double ifcb_inverter_fl_actual_values2_amk_igbt_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool ifcb_inverter_fl_actual_values2_amk_igbt_temp_is_in_range(int16_t value)
{
    return ((value >= -32760) && (value <= 32760));
}

int ifcb_inverter_rr_actual_values1_pack(
    uint8_t *dst_p,
    const struct ifcb_inverter_rr_actual_values1_t *src_p,
    size_t size)
{
    uint16_t amk_actual_velocity;
    uint16_t amk_magnetizing_current;
    uint16_t amk_torque_current;
    uint8_t amk_dc_on;
    uint8_t amk_derating;
    uint8_t amk_error;
    uint8_t amk_inverter_on;
    uint8_t amk_quit_dc_on;
    uint8_t amk_quit_inverter_on;
    uint8_t amk_system_ready;
    uint8_t amk_warning;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    amk_system_ready = (uint8_t)src_p->amk_system_ready;
    dst_p[1] |= pack_left_shift_u8(amk_system_ready, 0u, 0x01u);
    amk_error = (uint8_t)src_p->amk_error;
    dst_p[1] |= pack_left_shift_u8(amk_error, 1u, 0x02u);
    amk_warning = (uint8_t)src_p->amk_warning;
    dst_p[1] |= pack_left_shift_u8(amk_warning, 2u, 0x04u);
    amk_quit_dc_on = (uint8_t)src_p->amk_quit_dc_on;
    dst_p[1] |= pack_left_shift_u8(amk_quit_dc_on, 3u, 0x08u);
    amk_dc_on = (uint8_t)src_p->amk_dc_on;
    dst_p[1] |= pack_left_shift_u8(amk_dc_on, 4u, 0x10u);
    amk_quit_inverter_on = (uint8_t)src_p->amk_quit_inverter_on;
    dst_p[1] |= pack_left_shift_u8(amk_quit_inverter_on, 5u, 0x20u);
    amk_inverter_on = (uint8_t)src_p->amk_inverter_on;
    dst_p[1] |= pack_left_shift_u8(amk_inverter_on, 6u, 0x40u);
    amk_derating = (uint8_t)src_p->amk_derating;
    dst_p[1] |= pack_left_shift_u8(amk_derating, 7u, 0x80u);
    amk_actual_velocity = (uint16_t)src_p->amk_actual_velocity;
    dst_p[2] |= pack_left_shift_u16(amk_actual_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(amk_actual_velocity, 8u, 0xffu);
    amk_torque_current = (uint16_t)src_p->amk_torque_current;
    dst_p[4] |= pack_left_shift_u16(amk_torque_current, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(amk_torque_current, 8u, 0xffu);
    amk_magnetizing_current = (uint16_t)src_p->amk_magnetizing_current;
    dst_p[6] |= pack_left_shift_u16(amk_magnetizing_current, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(amk_magnetizing_current, 8u, 0xffu);

    return (8);
}

int ifcb_inverter_rr_actual_values1_unpack(
    struct ifcb_inverter_rr_actual_values1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t amk_actual_velocity;
    uint16_t amk_magnetizing_current;
    uint16_t amk_torque_current;
    uint8_t amk_dc_on;
    uint8_t amk_derating;
    uint8_t amk_error;
    uint8_t amk_inverter_on;
    uint8_t amk_quit_dc_on;
    uint8_t amk_quit_inverter_on;
    uint8_t amk_system_ready;
    uint8_t amk_warning;

    if (size < 8u) {
        return (-EINVAL);
    }

    amk_system_ready = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    if ((amk_system_ready & (1u << 0)) != 0u) {
        amk_system_ready |= 0xfeu;
    }

    dst_p->amk_system_ready = (int8_t)amk_system_ready;
    amk_error = unpack_right_shift_u8(src_p[1], 1u, 0x02u);

    if ((amk_error & (1u << 0)) != 0u) {
        amk_error |= 0xfeu;
    }

    dst_p->amk_error = (int8_t)amk_error;
    amk_warning = unpack_right_shift_u8(src_p[1], 2u, 0x04u);

    if ((amk_warning & (1u << 0)) != 0u) {
        amk_warning |= 0xfeu;
    }

    dst_p->amk_warning = (int8_t)amk_warning;
    amk_quit_dc_on = unpack_right_shift_u8(src_p[1], 3u, 0x08u);

    if ((amk_quit_dc_on & (1u << 0)) != 0u) {
        amk_quit_dc_on |= 0xfeu;
    }

    dst_p->amk_quit_dc_on = (int8_t)amk_quit_dc_on;
    amk_dc_on = unpack_right_shift_u8(src_p[1], 4u, 0x10u);

    if ((amk_dc_on & (1u << 0)) != 0u) {
        amk_dc_on |= 0xfeu;
    }

    dst_p->amk_dc_on = (int8_t)amk_dc_on;
    amk_quit_inverter_on = unpack_right_shift_u8(src_p[1], 5u, 0x20u);

    if ((amk_quit_inverter_on & (1u << 0)) != 0u) {
        amk_quit_inverter_on |= 0xfeu;
    }

    dst_p->amk_quit_inverter_on = (int8_t)amk_quit_inverter_on;
    amk_inverter_on = unpack_right_shift_u8(src_p[1], 6u, 0x40u);

    if ((amk_inverter_on & (1u << 0)) != 0u) {
        amk_inverter_on |= 0xfeu;
    }

    dst_p->amk_inverter_on = (int8_t)amk_inverter_on;
    amk_derating = unpack_right_shift_u8(src_p[1], 7u, 0x80u);

    if ((amk_derating & (1u << 0)) != 0u) {
        amk_derating |= 0xfeu;
    }

    dst_p->amk_derating = (int8_t)amk_derating;
    amk_actual_velocity = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    amk_actual_velocity |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->amk_actual_velocity = (int16_t)amk_actual_velocity;
    amk_torque_current = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    amk_torque_current |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->amk_torque_current = (int16_t)amk_torque_current;
    amk_magnetizing_current = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    amk_magnetizing_current |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->amk_magnetizing_current = (int16_t)amk_magnetizing_current;

    return (0);
}

int ifcb_inverter_rr_actual_values1_init(struct ifcb_inverter_rr_actual_values1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ifcb_inverter_rr_actual_values1_t));

    return 0;
}

int8_t ifcb_inverter_rr_actual_values1_amk_system_ready_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rr_actual_values1_amk_system_ready_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rr_actual_values1_amk_system_ready_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_rr_actual_values1_amk_error_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rr_actual_values1_amk_error_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rr_actual_values1_amk_error_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_rr_actual_values1_amk_warning_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rr_actual_values1_amk_warning_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rr_actual_values1_amk_warning_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_rr_actual_values1_amk_quit_dc_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rr_actual_values1_amk_quit_dc_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rr_actual_values1_amk_quit_dc_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_rr_actual_values1_amk_dc_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rr_actual_values1_amk_dc_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rr_actual_values1_amk_dc_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_rr_actual_values1_amk_quit_inverter_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rr_actual_values1_amk_quit_inverter_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rr_actual_values1_amk_quit_inverter_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_rr_actual_values1_amk_inverter_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rr_actual_values1_amk_inverter_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rr_actual_values1_amk_inverter_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_rr_actual_values1_amk_derating_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_rr_actual_values1_amk_derating_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rr_actual_values1_amk_derating_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int16_t ifcb_inverter_rr_actual_values1_amk_actual_velocity_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_inverter_rr_actual_values1_amk_actual_velocity_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rr_actual_values1_amk_actual_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_inverter_rr_actual_values1_amk_torque_current_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_inverter_rr_actual_values1_amk_torque_current_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rr_actual_values1_amk_torque_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_inverter_rr_actual_values1_amk_magnetizing_current_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_inverter_rr_actual_values1_amk_magnetizing_current_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rr_actual_values1_amk_magnetizing_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ifcb_inverter_fr_actual_values1_pack(
    uint8_t *dst_p,
    const struct ifcb_inverter_fr_actual_values1_t *src_p,
    size_t size)
{
    uint16_t amk_actual_velocity;
    uint16_t amk_magnetizing_current;
    uint16_t amk_torque_current;
    uint8_t amk_dc_on;
    uint8_t amk_derating;
    uint8_t amk_error;
    uint8_t amk_inverter_on;
    uint8_t amk_quit_dc_on;
    uint8_t amk_quit_inverter_on;
    uint8_t amk_system_ready;
    uint8_t amk_warning;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    amk_system_ready = (uint8_t)src_p->amk_system_ready;
    dst_p[1] |= pack_left_shift_u8(amk_system_ready, 0u, 0x01u);
    amk_error = (uint8_t)src_p->amk_error;
    dst_p[1] |= pack_left_shift_u8(amk_error, 1u, 0x02u);
    amk_warning = (uint8_t)src_p->amk_warning;
    dst_p[1] |= pack_left_shift_u8(amk_warning, 2u, 0x04u);
    amk_quit_dc_on = (uint8_t)src_p->amk_quit_dc_on;
    dst_p[1] |= pack_left_shift_u8(amk_quit_dc_on, 3u, 0x08u);
    amk_dc_on = (uint8_t)src_p->amk_dc_on;
    dst_p[1] |= pack_left_shift_u8(amk_dc_on, 4u, 0x10u);
    amk_quit_inverter_on = (uint8_t)src_p->amk_quit_inverter_on;
    dst_p[1] |= pack_left_shift_u8(amk_quit_inverter_on, 5u, 0x20u);
    amk_inverter_on = (uint8_t)src_p->amk_inverter_on;
    dst_p[1] |= pack_left_shift_u8(amk_inverter_on, 6u, 0x40u);
    amk_derating = (uint8_t)src_p->amk_derating;
    dst_p[1] |= pack_left_shift_u8(amk_derating, 7u, 0x80u);
    amk_actual_velocity = (uint16_t)src_p->amk_actual_velocity;
    dst_p[2] |= pack_left_shift_u16(amk_actual_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(amk_actual_velocity, 8u, 0xffu);
    amk_torque_current = (uint16_t)src_p->amk_torque_current;
    dst_p[4] |= pack_left_shift_u16(amk_torque_current, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(amk_torque_current, 8u, 0xffu);
    amk_magnetizing_current = (uint16_t)src_p->amk_magnetizing_current;
    dst_p[6] |= pack_left_shift_u16(amk_magnetizing_current, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(amk_magnetizing_current, 8u, 0xffu);

    return (8);
}

int ifcb_inverter_fr_actual_values1_unpack(
    struct ifcb_inverter_fr_actual_values1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t amk_actual_velocity;
    uint16_t amk_magnetizing_current;
    uint16_t amk_torque_current;
    uint8_t amk_dc_on;
    uint8_t amk_derating;
    uint8_t amk_error;
    uint8_t amk_inverter_on;
    uint8_t amk_quit_dc_on;
    uint8_t amk_quit_inverter_on;
    uint8_t amk_system_ready;
    uint8_t amk_warning;

    if (size < 8u) {
        return (-EINVAL);
    }

    amk_system_ready = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    if ((amk_system_ready & (1u << 0)) != 0u) {
        amk_system_ready |= 0xfeu;
    }

    dst_p->amk_system_ready = (int8_t)amk_system_ready;
    amk_error = unpack_right_shift_u8(src_p[1], 1u, 0x02u);

    if ((amk_error & (1u << 0)) != 0u) {
        amk_error |= 0xfeu;
    }

    dst_p->amk_error = (int8_t)amk_error;
    amk_warning = unpack_right_shift_u8(src_p[1], 2u, 0x04u);

    if ((amk_warning & (1u << 0)) != 0u) {
        amk_warning |= 0xfeu;
    }

    dst_p->amk_warning = (int8_t)amk_warning;
    amk_quit_dc_on = unpack_right_shift_u8(src_p[1], 3u, 0x08u);

    if ((amk_quit_dc_on & (1u << 0)) != 0u) {
        amk_quit_dc_on |= 0xfeu;
    }

    dst_p->amk_quit_dc_on = (int8_t)amk_quit_dc_on;
    amk_dc_on = unpack_right_shift_u8(src_p[1], 4u, 0x10u);

    if ((amk_dc_on & (1u << 0)) != 0u) {
        amk_dc_on |= 0xfeu;
    }

    dst_p->amk_dc_on = (int8_t)amk_dc_on;
    amk_quit_inverter_on = unpack_right_shift_u8(src_p[1], 5u, 0x20u);

    if ((amk_quit_inverter_on & (1u << 0)) != 0u) {
        amk_quit_inverter_on |= 0xfeu;
    }

    dst_p->amk_quit_inverter_on = (int8_t)amk_quit_inverter_on;
    amk_inverter_on = unpack_right_shift_u8(src_p[1], 6u, 0x40u);

    if ((amk_inverter_on & (1u << 0)) != 0u) {
        amk_inverter_on |= 0xfeu;
    }

    dst_p->amk_inverter_on = (int8_t)amk_inverter_on;
    amk_derating = unpack_right_shift_u8(src_p[1], 7u, 0x80u);

    if ((amk_derating & (1u << 0)) != 0u) {
        amk_derating |= 0xfeu;
    }

    dst_p->amk_derating = (int8_t)amk_derating;
    amk_actual_velocity = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    amk_actual_velocity |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->amk_actual_velocity = (int16_t)amk_actual_velocity;
    amk_torque_current = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    amk_torque_current |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->amk_torque_current = (int16_t)amk_torque_current;
    amk_magnetizing_current = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    amk_magnetizing_current |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->amk_magnetizing_current = (int16_t)amk_magnetizing_current;

    return (0);
}

int ifcb_inverter_fr_actual_values1_init(struct ifcb_inverter_fr_actual_values1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ifcb_inverter_fr_actual_values1_t));

    return 0;
}

int8_t ifcb_inverter_fr_actual_values1_amk_system_ready_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fr_actual_values1_amk_system_ready_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fr_actual_values1_amk_system_ready_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_fr_actual_values1_amk_error_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fr_actual_values1_amk_error_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fr_actual_values1_amk_error_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_fr_actual_values1_amk_warning_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fr_actual_values1_amk_warning_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fr_actual_values1_amk_warning_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_fr_actual_values1_amk_quit_dc_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fr_actual_values1_amk_quit_dc_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fr_actual_values1_amk_quit_dc_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_fr_actual_values1_amk_dc_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fr_actual_values1_amk_dc_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fr_actual_values1_amk_dc_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_fr_actual_values1_amk_quit_inverter_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fr_actual_values1_amk_quit_inverter_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fr_actual_values1_amk_quit_inverter_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_fr_actual_values1_amk_inverter_on_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fr_actual_values1_amk_inverter_on_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fr_actual_values1_amk_inverter_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t ifcb_inverter_fr_actual_values1_amk_derating_encode(double value)
{
    return (int8_t)(value);
}

double ifcb_inverter_fr_actual_values1_amk_derating_decode(int8_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fr_actual_values1_amk_derating_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int16_t ifcb_inverter_fr_actual_values1_amk_actual_velocity_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_inverter_fr_actual_values1_amk_actual_velocity_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fr_actual_values1_amk_actual_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_inverter_fr_actual_values1_amk_torque_current_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_inverter_fr_actual_values1_amk_torque_current_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fr_actual_values1_amk_torque_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_inverter_fr_actual_values1_amk_magnetizing_current_encode(double value)
{
    return (int16_t)(value);
}

double ifcb_inverter_fr_actual_values1_amk_magnetizing_current_decode(int16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fr_actual_values1_amk_magnetizing_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ifcb_inverter_rr_actual_values2_pack(
    uint8_t *dst_p,
    const struct ifcb_inverter_rr_actual_values2_t *src_p,
    size_t size)
{
    uint16_t amk_igbt_temp;
    uint16_t amk_temp_inverter;
    uint16_t amk_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    amk_temp_motor = (uint16_t)src_p->amk_temp_motor;
    dst_p[0] |= pack_left_shift_u16(amk_temp_motor, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(amk_temp_motor, 8u, 0xffu);
    amk_temp_inverter = (uint16_t)src_p->amk_temp_inverter;
    dst_p[2] |= pack_left_shift_u16(amk_temp_inverter, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(amk_temp_inverter, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->amk_error_info, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->amk_error_info, 8u, 0xffu);
    amk_igbt_temp = (uint16_t)src_p->amk_igbt_temp;
    dst_p[6] |= pack_left_shift_u16(amk_igbt_temp, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(amk_igbt_temp, 8u, 0xffu);

    return (8);
}

int ifcb_inverter_rr_actual_values2_unpack(
    struct ifcb_inverter_rr_actual_values2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t amk_igbt_temp;
    uint16_t amk_temp_inverter;
    uint16_t amk_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    amk_temp_motor = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    amk_temp_motor |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->amk_temp_motor = (int16_t)amk_temp_motor;
    amk_temp_inverter = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    amk_temp_inverter |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->amk_temp_inverter = (int16_t)amk_temp_inverter;
    dst_p->amk_error_info = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->amk_error_info |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    amk_igbt_temp = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    amk_igbt_temp |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->amk_igbt_temp = (int16_t)amk_igbt_temp;

    return (0);
}

int ifcb_inverter_rr_actual_values2_init(struct ifcb_inverter_rr_actual_values2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ifcb_inverter_rr_actual_values2_t));

    return 0;
}

int16_t ifcb_inverter_rr_actual_values2_amk_temp_motor_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double ifcb_inverter_rr_actual_values2_amk_temp_motor_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool ifcb_inverter_rr_actual_values2_amk_temp_motor_is_in_range(int16_t value)
{
    return ((value >= -32760) && (value <= 32760));
}

int16_t ifcb_inverter_rr_actual_values2_amk_temp_inverter_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double ifcb_inverter_rr_actual_values2_amk_temp_inverter_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool ifcb_inverter_rr_actual_values2_amk_temp_inverter_is_in_range(int16_t value)
{
    return ((value >= -32760) && (value <= 32760));
}

uint16_t ifcb_inverter_rr_actual_values2_amk_error_info_encode(double value)
{
    return (uint16_t)(value);
}

double ifcb_inverter_rr_actual_values2_amk_error_info_decode(uint16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_rr_actual_values2_amk_error_info_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_inverter_rr_actual_values2_amk_igbt_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double ifcb_inverter_rr_actual_values2_amk_igbt_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool ifcb_inverter_rr_actual_values2_amk_igbt_temp_is_in_range(int16_t value)
{
    return ((value >= -32760) && (value <= 32760));
}

int ifcb_inverter_fr_actual_values2_pack(
    uint8_t *dst_p,
    const struct ifcb_inverter_fr_actual_values2_t *src_p,
    size_t size)
{
    uint16_t amk_igbt_temp;
    uint16_t amk_temp_inverter;
    uint16_t amk_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    amk_temp_motor = (uint16_t)src_p->amk_temp_motor;
    dst_p[0] |= pack_left_shift_u16(amk_temp_motor, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(amk_temp_motor, 8u, 0xffu);
    amk_temp_inverter = (uint16_t)src_p->amk_temp_inverter;
    dst_p[2] |= pack_left_shift_u16(amk_temp_inverter, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(amk_temp_inverter, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->amk_error_info, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->amk_error_info, 8u, 0xffu);
    amk_igbt_temp = (uint16_t)src_p->amk_igbt_temp;
    dst_p[6] |= pack_left_shift_u16(amk_igbt_temp, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(amk_igbt_temp, 8u, 0xffu);

    return (8);
}

int ifcb_inverter_fr_actual_values2_unpack(
    struct ifcb_inverter_fr_actual_values2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t amk_igbt_temp;
    uint16_t amk_temp_inverter;
    uint16_t amk_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    amk_temp_motor = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    amk_temp_motor |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->amk_temp_motor = (int16_t)amk_temp_motor;
    amk_temp_inverter = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    amk_temp_inverter |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->amk_temp_inverter = (int16_t)amk_temp_inverter;
    dst_p->amk_error_info = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->amk_error_info |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    amk_igbt_temp = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    amk_igbt_temp |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->amk_igbt_temp = (int16_t)amk_igbt_temp;

    return (0);
}

int ifcb_inverter_fr_actual_values2_init(struct ifcb_inverter_fr_actual_values2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ifcb_inverter_fr_actual_values2_t));

    return 0;
}

int16_t ifcb_inverter_fr_actual_values2_amk_temp_motor_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double ifcb_inverter_fr_actual_values2_amk_temp_motor_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool ifcb_inverter_fr_actual_values2_amk_temp_motor_is_in_range(int16_t value)
{
    return ((value >= -32760) && (value <= 32760));
}

int16_t ifcb_inverter_fr_actual_values2_amk_temp_inverter_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double ifcb_inverter_fr_actual_values2_amk_temp_inverter_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool ifcb_inverter_fr_actual_values2_amk_temp_inverter_is_in_range(int16_t value)
{
    return ((value >= -32760) && (value <= 32760));
}

uint16_t ifcb_inverter_fr_actual_values2_amk_error_info_encode(double value)
{
    return (uint16_t)(value);
}

double ifcb_inverter_fr_actual_values2_amk_error_info_decode(uint16_t value)
{
    return ((double)value);
}

bool ifcb_inverter_fr_actual_values2_amk_error_info_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t ifcb_inverter_fr_actual_values2_amk_igbt_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double ifcb_inverter_fr_actual_values2_amk_igbt_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool ifcb_inverter_fr_actual_values2_amk_igbt_temp_is_in_range(int16_t value)
{
    return ((value >= -32760) && (value <= 32760));
}
