name: Generate acmelib Files

on:
  push:
    branches: ["acmelib"]
    paths:
      - "SC24/artifacts/MCB/MCB.dbc"

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup generated folder
        run: |
          mkdir -p SC24_acmelib/generated
          touch SC24_acmelib/generated/MCB.dbc
          touch SC24_acmelib/generated/SC24.json
          touch SC24_acmelib/generated/SC24.binpb
          touch SC24_acmelib/generated/SC24.md
          ls -l

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Run Go Script
        run: |
          cd SC24_acmelib
          go run .
          ls -l
          cd ..

      - name: Commit and Push Changes
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add SC24_acmelib/generated
          git commit -m "Update from JSON"
          git push
